version: '3.4'

services:
  raymon.loginapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  raymon.registerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  raymon.weatherapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

